spring:
  application:
    name: course-center
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.25.149.156:3306/db_su?serverTimezone=Asia/Shanghai
    username: root
    password: suroot
#    url: jdbc:mysql://localhost:3306/db_s?serverTimezone=Asia/Shanghai
#    username: root
#    password: root

    hikari:
      # 最小连接数
      minimum-idle: 1
      # 最大连接数
      maximum-pool-size: 200
      # 自动提交
      auto-commit: true
      # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      idle-timeout: 10000
      # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      max-lifetime: 1800000
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: 30000
      # 连接测试查询语句
      connection-test-query: SELECT 1
server:
  port: 9002

mybatis:
  configuration:
    map-underscore-to-camel-case: true
