server:
  port: 9001
spring:
  application:
    name: content-center
#  zipkin:
#    base-url: http://120.25.149.156:9411/
#    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1.0
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://120.25.149.156:3306/content_center
    hikari:
      username: root
      password: suroot
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 最小连接数
      minimum-idle: 1
      # 最大连接数
      maximum-pool-size: 200
      # 自动提交
      auto-commit: true
      # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      idle-timeout: 100000
      # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      max-lifetime: 1800000
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: 300000
      # 连接测试查询语句
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        #指定nacos server地址
        server-addr: 120.25.149.156:8848
#        namespace: 44675539-ace5-4399-b169-ff9f166579b2
        metadata:
          instance: su
          hello: world
          version: 1.0
    #    服务容错
    sentinel:
      transport:
        dashboard: localhost:8080


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

#ribbon随机生成策略代码配置
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#饥饿加载配置
ribbon:
  eager-load:
    enabled: true
    clients: user-center

mybatis:
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    com.soft1851.content.center.feignclient.UserCenterFeignClient: debug
    org.springframework.cloud.sleuth: debug
  #feign日志配置
  feign:
    sentinel:
      #为feign整合sentinel
      enabled: true
    client:
      config:
  #      全局配置
        default:
          loggerLevel: full
#          配置feign的拦截器，让token可以在各个微服务之间传递
          requestInterceptor:
            - com.soft1851.content.center.feignclient.TonkenInterceptor
  httpclient:
    #    让feign使用apache httpclient做请求； 而不是默认的URL connection
    enabled: true
    #    feign的最大连接数
    max-connections: 200
    #    feign单个路劲的最大连接数
    max-connections-per-route: 50

rocketmq:
  name-server: 120.25.149.156:9876
  producer:
    group: test-group
