server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 120.25.149.156:8848
#        namespace: 44675539-ace5-4399-b169-ff9f166579b2
    gateway:
      discovery:
        locator:
#          让gateway通过服务发现组件找到其他的微服务
          enabled: true
      routes:
        - id: path_route1
          uri: lb://user-center
          predicates:
            - Path=/users/**

        - id: path_route2
          uri: lb://content-center
          predicates:
            - Path=/shares/**
        - id: path_route3
          uri: lb://content-center
          predicates:
            - Path=/notices/**
        - id: path_route4
          uri: lb://content-center
          predicates:
            - Path=/admin/**
#        带有指定Cookie的请求会匹配该路由。
#      - id: cookie_route
#        uri: lb://user-center
#        predicates:
#          - Cookie=username,macro
#
#      - id: path_route
#        uri: lb://user-center
#        predicates:
#          - Path=/users/{id}
#
#      - id: after_route
#        uri: lb://content-center
#        predicates:
#          - After=2020-10-09T09:30:00+08:00[Asia/Shanghai]
#
##        带有指定Cookie的请求会匹配该路由。
#      - id: cookie_route
#        uri: lb://user-center
#        predicates:
#          - Cookie=username,macro
##      带有指定请求头的请求会匹配该路由。
#      - id: header_route
#        uri: lb://user-center
#        predicates:
#          - TimeBetween=上午9:00,下午5:00
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: trace