server:
  port: 9103


spring:
  application:
    name: user-center
  zipkin:
    base-url: http://120.25.149.156:9411/
    discovery-client-enabled: false
    sleuth:
      sampler:
        probability: 1.0
  datasource:
    url: jdbc:mysql://120.25.149.156:3306/user_center
    hikari:
      username: root
      password: suroot
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 最小连接数
      minimum-idle: 1
      # 最大连接数
      maximum-pool-size: 200
      # 自动提交
      auto-commit: true
      # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      idle-timeout: 10000
      # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      max-lifetime: 1800000
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: 30000
      # 连接测试查询语句
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        #指定nacos server地址
        server-addr: 120.25.149.156:8848
#        nacos自定义命名空间
#        namespace: 44675539-ace5-4399-b169-ff9f166579b2

mybatis:
  configuration:
    map-underscore-to-camel-case: true


rocketmq:
  name-server: 120.25.149.156:9876

jwt:
  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
  expire-time-in-second: 1209600
